---
# 還原環境的指令稿
- hosts: "{{ target_host }}"
  vars_files:
    - ./vars-credentials.yml
  tasks:
    # 還原的流程設計是要先透過建置 wordpress 環境的伺服器準備運作環境，然後再引入這份指令稿還原伺服器，
    # 而不像 setup-wordpress 的建置流程會透過 wp-cli 下載指定版本的 wordpress。

    # 設定伺服器
    - include: ../configure-server/configure-server.yml

    - name: 停止 httpd 的服務
      service:
        name: httpd
        state: stopped
      become: yes
      become_user: root

    - name: 先清空可能存放先前用來還原其他資料的目錄
      file:
        path: /tmp/latest
        state: absent
      become: yes
      become_user: root

    - name: 解壓縮要回復的版本
      unarchive:
        copy: yes
        src: ./backup.gz
        dest: /tmp
        mode: 0754

    # 先還原資料庫

    - name: 啟用資料庫
      service:
        name: mariadb
        state: started
      become: yes
      become_user: root
    
    - name: 倒資料回資料庫
      mysql_db:
        state: import
        name: "{{ wp_db_name }}"
        target: /tmp/latest/backup.sql
        login_user: "{{ mariadb_wp_user }}"
        login_password: "{{ mariadb_wp_user_pwd }}"
    
    - name: 刪除已用來倒完系統資料的 sql 檔
      file:
        name: /tmp/latest/backup.sql
        state: absent

    - name: 傳送更新 siteurl 和 home 的 sql 到還原資料目錄
      template:
        src: ./update-siteurl-and-home.sql.j2
        dest: /tmp/latest/update-siteurl-and-home.sql
        mode: 0754
    
    - name: 更新 wordpress 的 siteurl 和 home
      mysql_db:
        name: "{{ wp_db_name }}"
        state: import
        target: /tmp/latest/update-siteurl-and-home.sql
        login_user: "{{ mariadb_wp_user }}"
        login_password: "{{ mariadb_wp_user_pwd }}"

    - name: 刪除已用來更新系統網域名稱的 sql 檔
      file:
        name: /tmp/latest/update-siteurl-and-home.sql
        state: absent

    # 安全起見，還原前要先刪除已在部署位置的執行檔以免版本錯亂
    - name: 刪除在部署位置的執行檔
      file:
        name: "{{ project_path }}{{ host_name }}"
        state: absent
      become: yes
      become_user: root

    - name: 產生要佈署系統執行檔的資料匣
      file:
        path: "{{ project_path }}{{ host_name }}"
        state: directory
      become: yes
      become_user: root

    - name: 送系統執行檔到部署位置
      shell: "rsync -rlgo /tmp/latest/* {{ project_path }}{{ host_name }} --specials"
      # 這些 rsync 參數的意義
      # -r, --recursive             recurse into directories
      # -l, --links                 copy symlinks as symlinks
      # -o, --owner                 preserve owner (super-user only)
      # -g, --group                 preserve group
      # --specials              preserve special files
      # --exclude=PATTERN       exclude files matching PATTERN
      become: yes
      become_user: root

    - name: 刪除還原資料夾
      file:
        path: /tmp/latest
        state: absent

    - name: 設定系統執行檔的擁有者和群組皆為 root
      file:
        path: "{{ project_path }}{{ host_name }}"
        owner: root
        group: root
        recurse: true
        state: directory
        # 要提供其他使用者 execute 權限，否則 httpd 會無法讀取檔案提供服務
        mode: 0755
      become: yes
      become_user: root
    
    - name: 開放 apache 存取專案錄的權限以利後續手動更新套件
      acl:
        path: "{{ project_path }}{{ host_name }}"
        state: present
        # 以下這會讓目標目錄「未來增加」的子目錄都繼承目前的 acl 設定
        default: yes
        # recursive 與 default 的差別在於 recursive 使「目前」的子目錄都繼承目前的 acl 設定
        recursive: yes
        entity: apache
        etype: group
        permissions: rwx
      become: true
      become_user: root

    - name: 啟動 httpd
      service:
        name: httpd
        state: started
      become: yes
      become_user: root

    # 設定按時自動備份 wordpress 的排程
    - include: ../setup-wordpress-backup-scedule/setup-wordpress-backup-scedule.yml
